//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kingsun.SmarterClassroom.API.BigDataService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyLogMonitorAdd", Namespace="http://schemas.datacontract.org/2004/07/Fz.BigData.WCF")]
    [System.SerializableAttribute()]
    public partial class SyLogMonitorAdd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControllerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HttpMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RenderTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ResponseTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionName {
            get {
                return this.ActionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionNameField, value) != true)) {
                    this.ActionNameField = value;
                    this.RaisePropertyChanged("ActionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControllerName {
            get {
                return this.ControllerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ControllerNameField, value) != true)) {
                    this.ControllerNameField = value;
                    this.RaisePropertyChanged("ControllerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateAccount {
            get {
                return this.CreateAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateAccountField, value) != true)) {
                    this.CreateAccountField = value;
                    this.RaisePropertyChanged("CreateAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateIp {
            get {
                return this.CreateIpField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateIpField, value) != true)) {
                    this.CreateIpField = value;
                    this.RaisePropertyChanged("CreateIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserName {
            get {
                return this.CreateUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserNameField, value) != true)) {
                    this.CreateUserNameField = value;
                    this.RaisePropertyChanged("CreateUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HttpMethod {
            get {
                return this.HttpMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.HttpMethodField, value) != true)) {
                    this.HttpMethodField = value;
                    this.RaisePropertyChanged("HttpMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RenderTime {
            get {
                return this.RenderTimeField;
            }
            set {
                if ((this.RenderTimeField.Equals(value) != true)) {
                    this.RenderTimeField = value;
                    this.RaisePropertyChanged("RenderTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ResponseTime {
            get {
                return this.ResponseTimeField;
            }
            set {
                if ((this.ResponseTimeField.Equals(value) != true)) {
                    this.ResponseTimeField = value;
                    this.RaisePropertyChanged("ResponseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyLogMonitorList", Namespace="http://schemas.datacontract.org/2004/07/Fz.BigData.WCF")]
    [System.SerializableAttribute()]
    public partial class SyLogMonitorList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControllerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HttpMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> RenderTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> ResponseTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> TotalTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionName {
            get {
                return this.ActionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionNameField, value) != true)) {
                    this.ActionNameField = value;
                    this.RaisePropertyChanged("ActionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControllerName {
            get {
                return this.ControllerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ControllerNameField, value) != true)) {
                    this.ControllerNameField = value;
                    this.RaisePropertyChanged("ControllerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateAccount {
            get {
                return this.CreateAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateAccountField, value) != true)) {
                    this.CreateAccountField = value;
                    this.RaisePropertyChanged("CreateAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateIp {
            get {
                return this.CreateIpField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateIpField, value) != true)) {
                    this.CreateIpField = value;
                    this.RaisePropertyChanged("CreateIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserName {
            get {
                return this.CreateUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserNameField, value) != true)) {
                    this.CreateUserNameField = value;
                    this.RaisePropertyChanged("CreateUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DType {
            get {
                return this.DTypeField;
            }
            set {
                if ((this.DTypeField.Equals(value) != true)) {
                    this.DTypeField = value;
                    this.RaisePropertyChanged("DType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HttpMethod {
            get {
                return this.HttpMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.HttpMethodField, value) != true)) {
                    this.HttpMethodField = value;
                    this.RaisePropertyChanged("HttpMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> RenderTime {
            get {
                return this.RenderTimeField;
            }
            set {
                if ((this.RenderTimeField.Equals(value) != true)) {
                    this.RenderTimeField = value;
                    this.RaisePropertyChanged("RenderTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> ResponseTime {
            get {
                return this.ResponseTimeField;
            }
            set {
                if ((this.ResponseTimeField.Equals(value) != true)) {
                    this.ResponseTimeField = value;
                    this.RaisePropertyChanged("ResponseTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> TotalTime {
            get {
                return this.TotalTimeField;
            }
            set {
                if ((this.TotalTimeField.Equals(value) != true)) {
                    this.TotalTimeField = value;
                    this.RaisePropertyChanged("TotalTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyLogErrorAdd", Namespace="http://schemas.datacontract.org/2004/07/Fz.BigData.WCF")]
    [System.SerializableAttribute()]
    public partial class SyLogErrorAdd : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControllerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HttpMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionName {
            get {
                return this.ActionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionNameField, value) != true)) {
                    this.ActionNameField = value;
                    this.RaisePropertyChanged("ActionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControllerName {
            get {
                return this.ControllerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ControllerNameField, value) != true)) {
                    this.ControllerNameField = value;
                    this.RaisePropertyChanged("ControllerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateAccount {
            get {
                return this.CreateAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateAccountField, value) != true)) {
                    this.CreateAccountField = value;
                    this.RaisePropertyChanged("CreateAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateIp {
            get {
                return this.CreateIpField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateIpField, value) != true)) {
                    this.CreateIpField = value;
                    this.RaisePropertyChanged("CreateIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserName {
            get {
                return this.CreateUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserNameField, value) != true)) {
                    this.CreateUserNameField = value;
                    this.RaisePropertyChanged("CreateUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HttpMethod {
            get {
                return this.HttpMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.HttpMethodField, value) != true)) {
                    this.HttpMethodField = value;
                    this.RaisePropertyChanged("HttpMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SyLogErrorList", Namespace="http://schemas.datacontract.org/2004/07/Fz.BigData.WCF")]
    [System.SerializableAttribute()]
    public partial class SyLogErrorList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActionNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControllerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateAccountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateIpField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HttpMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActionName {
            get {
                return this.ActionNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ActionNameField, value) != true)) {
                    this.ActionNameField = value;
                    this.RaisePropertyChanged("ActionName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ControllerName {
            get {
                return this.ControllerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ControllerNameField, value) != true)) {
                    this.ControllerNameField = value;
                    this.RaisePropertyChanged("ControllerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateAccount {
            get {
                return this.CreateAccountField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateAccountField, value) != true)) {
                    this.CreateAccountField = value;
                    this.RaisePropertyChanged("CreateAccount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateIp {
            get {
                return this.CreateIpField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateIpField, value) != true)) {
                    this.CreateIpField = value;
                    this.RaisePropertyChanged("CreateIp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserName {
            get {
                return this.CreateUserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserNameField, value) != true)) {
                    this.CreateUserNameField = value;
                    this.RaisePropertyChanged("CreateUserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DType {
            get {
                return this.DTypeField;
            }
            set {
                if ((this.DTypeField.Equals(value) != true)) {
                    this.DTypeField = value;
                    this.RaisePropertyChanged("DType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HttpMethod {
            get {
                return this.HttpMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.HttpMethodField, value) != true)) {
                    this.HttpMethodField = value;
                    this.RaisePropertyChanged("HttpMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Url {
            get {
                return this.UrlField;
            }
            set {
                if ((object.ReferenceEquals(this.UrlField, value) != true)) {
                    this.UrlField = value;
                    this.RaisePropertyChanged("Url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RoomLogList", Namespace="http://schemas.datacontract.org/2004/07/Fz.BigData.WCF")]
    [System.SerializableAttribute()]
    public partial class RoomLogList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CreateUserTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int OperIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreateTime {
            get {
                return this.CreateTimeField;
            }
            set {
                if ((this.CreateTimeField.Equals(value) != true)) {
                    this.CreateTimeField = value;
                    this.RaisePropertyChanged("CreateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CreateUserType {
            get {
                return this.CreateUserTypeField;
            }
            set {
                if ((this.CreateUserTypeField.Equals(value) != true)) {
                    this.CreateUserTypeField = value;
                    this.RaisePropertyChanged("CreateUserType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id {
            get {
                return this.IdField;
            }
            set {
                if ((object.ReferenceEquals(this.IdField, value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperContent {
            get {
                return this.OperContentField;
            }
            set {
                if ((object.ReferenceEquals(this.OperContentField, value) != true)) {
                    this.OperContentField = value;
                    this.RaisePropertyChanged("OperContent");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int OperId {
            get {
                return this.OperIdField;
            }
            set {
                if ((this.OperIdField.Equals(value) != true)) {
                    this.OperIdField = value;
                    this.RaisePropertyChanged("OperId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BigDataService.IBigDataService")]
    public interface IBigDataService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogMonitorWeb_Add", ReplyAction="http://tempuri.org/IBigDataService/SyLogMonitorWeb_AddResponse")]
        void SyLogMonitorWeb_Add(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorAdd m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogMonitorWeb_Add", ReplyAction="http://tempuri.org/IBigDataService/SyLogMonitorWeb_AddResponse")]
        System.Threading.Tasks.Task SyLogMonitorWeb_AddAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorAdd m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogMonitorApi_Add", ReplyAction="http://tempuri.org/IBigDataService/SyLogMonitorApi_AddResponse")]
        void SyLogMonitorApi_Add(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorAdd m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogMonitorApi_Add", ReplyAction="http://tempuri.org/IBigDataService/SyLogMonitorApi_AddResponse")]
        System.Threading.Tasks.Task SyLogMonitorApi_AddAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorAdd m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogMonitor_GetList", ReplyAction="http://tempuri.org/IBigDataService/SyLogMonitor_GetListResponse")]
        Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListResponse SyLogMonitor_GetList(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogMonitor_GetList", ReplyAction="http://tempuri.org/IBigDataService/SyLogMonitor_GetListResponse")]
        System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListResponse> SyLogMonitor_GetListAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogOper_GetList", ReplyAction="http://tempuri.org/IBigDataService/SyLogOper_GetListResponse")]
        Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListResponse SyLogOper_GetList(Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogOper_GetList", ReplyAction="http://tempuri.org/IBigDataService/SyLogOper_GetListResponse")]
        System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListResponse> SyLogOper_GetListAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogErrorWeb_Add", ReplyAction="http://tempuri.org/IBigDataService/SyLogErrorWeb_AddResponse")]
        void SyLogErrorWeb_Add(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorAdd m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogErrorWeb_Add", ReplyAction="http://tempuri.org/IBigDataService/SyLogErrorWeb_AddResponse")]
        System.Threading.Tasks.Task SyLogErrorWeb_AddAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorAdd m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogErrorApi_Add", ReplyAction="http://tempuri.org/IBigDataService/SyLogErrorApi_AddResponse")]
        void SyLogErrorApi_Add(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorAdd m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogErrorApi_Add", ReplyAction="http://tempuri.org/IBigDataService/SyLogErrorApi_AddResponse")]
        System.Threading.Tasks.Task SyLogErrorApi_AddAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorAdd m);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogError_GetList", ReplyAction="http://tempuri.org/IBigDataService/SyLogError_GetListResponse")]
        Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListResponse SyLogError_GetList(Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/SyLogError_GetList", ReplyAction="http://tempuri.org/IBigDataService/SyLogError_GetListResponse")]
        System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListResponse> SyLogError_GetListAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_Add", ReplyAction="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_AddResponse")]
        void ClrLogMonitorWeb_Add(string userId, int userType, int OperId, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_Add", ReplyAction="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_AddResponse")]
        System.Threading.Tasks.Task ClrLogMonitorWeb_AddAsync(string userId, int userType, int OperId, string content);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_GetList", ReplyAction="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_GetListResponse")]
        Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListResponse ClrLogMonitorWeb_GetList(Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListRequest request);
        
        // CODEGEN: 正在生成消息协定，应为该操作具有多个返回值。
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_GetList", ReplyAction="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_GetListResponse")]
        System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListResponse> ClrLogMonitorWeb_GetListAsync(Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_GetListAll", ReplyAction="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_GetListAllResponse")]
        Kingsun.SmarterClassroom.API.BigDataService.RoomLogList[] ClrLogMonitorWeb_GetListAll(System.Nullable<System.DateTime> sdate, System.Nullable<System.DateTime> edate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_GetListAll", ReplyAction="http://tempuri.org/IBigDataService/ClrLogMonitorWeb_GetListAllResponse")]
        System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.RoomLogList[]> ClrLogMonitorWeb_GetListAllAsync(System.Nullable<System.DateTime> sdate, System.Nullable<System.DateTime> edate);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyLogMonitor_GetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyLogMonitor_GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<decimal> w_totalTime;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string controller;
        
        public SyLogMonitor_GetListRequest() {
        }
        
        public SyLogMonitor_GetListRequest(int pageIndex, int pageSize, System.Nullable<decimal> w_totalTime, string controller) {
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.w_totalTime = w_totalTime;
            this.controller = controller;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyLogMonitor_GetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyLogMonitor_GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorList[] SyLogMonitor_GetListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int total;
        
        public SyLogMonitor_GetListResponse() {
        }
        
        public SyLogMonitor_GetListResponse(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorList[] SyLogMonitor_GetListResult, int total) {
            this.SyLogMonitor_GetListResult = SyLogMonitor_GetListResult;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyLogOper_GetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyLogOper_GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string account;
        
        public SyLogOper_GetListRequest() {
        }
        
        public SyLogOper_GetListRequest(int pageIndex, int pageSize, string account) {
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.account = account;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyLogOper_GetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyLogOper_GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorList[] SyLogOper_GetListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int total;
        
        public SyLogOper_GetListResponse() {
        }
        
        public SyLogOper_GetListResponse(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorList[] SyLogOper_GetListResult, int total) {
            this.SyLogOper_GetListResult = SyLogOper_GetListResult;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyLogError_GetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyLogError_GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string controller;
        
        public SyLogError_GetListRequest() {
        }
        
        public SyLogError_GetListRequest(int pageIndex, int pageSize, string controller) {
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.controller = controller;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SyLogError_GetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class SyLogError_GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorList[] SyLogError_GetListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int total;
        
        public SyLogError_GetListResponse() {
        }
        
        public SyLogError_GetListResponse(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorList[] SyLogError_GetListResult, int total) {
            this.SyLogError_GetListResult = SyLogError_GetListResult;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClrLogMonitorWeb_GetList", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClrLogMonitorWeb_GetListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int pageIndex;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int pageSize;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public System.Nullable<System.DateTime> sdate;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.Nullable<System.DateTime> edate;
        
        public ClrLogMonitorWeb_GetListRequest() {
        }
        
        public ClrLogMonitorWeb_GetListRequest(int pageIndex, int pageSize, System.Nullable<System.DateTime> sdate, System.Nullable<System.DateTime> edate) {
            this.pageIndex = pageIndex;
            this.pageSize = pageSize;
            this.sdate = sdate;
            this.edate = edate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ClrLogMonitorWeb_GetListResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class ClrLogMonitorWeb_GetListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Kingsun.SmarterClassroom.API.BigDataService.RoomLogList[] ClrLogMonitorWeb_GetListResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public int total;
        
        public ClrLogMonitorWeb_GetListResponse() {
        }
        
        public ClrLogMonitorWeb_GetListResponse(Kingsun.SmarterClassroom.API.BigDataService.RoomLogList[] ClrLogMonitorWeb_GetListResult, int total) {
            this.ClrLogMonitorWeb_GetListResult = ClrLogMonitorWeb_GetListResult;
            this.total = total;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBigDataServiceChannel : Kingsun.SmarterClassroom.API.BigDataService.IBigDataService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BigDataServiceClient : System.ServiceModel.ClientBase<Kingsun.SmarterClassroom.API.BigDataService.IBigDataService>, Kingsun.SmarterClassroom.API.BigDataService.IBigDataService {
        
        public BigDataServiceClient() {
        }
        
        public BigDataServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BigDataServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BigDataServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BigDataServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void SyLogMonitorWeb_Add(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorAdd m) {
            base.Channel.SyLogMonitorWeb_Add(m);
        }
        
        public System.Threading.Tasks.Task SyLogMonitorWeb_AddAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorAdd m) {
            return base.Channel.SyLogMonitorWeb_AddAsync(m);
        }
        
        public void SyLogMonitorApi_Add(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorAdd m) {
            base.Channel.SyLogMonitorApi_Add(m);
        }
        
        public System.Threading.Tasks.Task SyLogMonitorApi_AddAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorAdd m) {
            return base.Channel.SyLogMonitorApi_AddAsync(m);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListResponse Kingsun.SmarterClassroom.API.BigDataService.IBigDataService.SyLogMonitor_GetList(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListRequest request) {
            return base.Channel.SyLogMonitor_GetList(request);
        }
        
        public Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorList[] SyLogMonitor_GetList(int pageIndex, int pageSize, System.Nullable<decimal> w_totalTime, string controller, out int total) {
            Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListRequest inValue = new Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListRequest();
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.w_totalTime = w_totalTime;
            inValue.controller = controller;
            Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListResponse retVal = ((Kingsun.SmarterClassroom.API.BigDataService.IBigDataService)(this)).SyLogMonitor_GetList(inValue);
            total = retVal.total;
            return retVal.SyLogMonitor_GetListResult;
        }
        
        public System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListResponse> SyLogMonitor_GetListAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitor_GetListRequest request) {
            return base.Channel.SyLogMonitor_GetListAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListResponse Kingsun.SmarterClassroom.API.BigDataService.IBigDataService.SyLogOper_GetList(Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListRequest request) {
            return base.Channel.SyLogOper_GetList(request);
        }
        
        public Kingsun.SmarterClassroom.API.BigDataService.SyLogMonitorList[] SyLogOper_GetList(int pageIndex, int pageSize, string account, out int total) {
            Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListRequest inValue = new Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListRequest();
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.account = account;
            Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListResponse retVal = ((Kingsun.SmarterClassroom.API.BigDataService.IBigDataService)(this)).SyLogOper_GetList(inValue);
            total = retVal.total;
            return retVal.SyLogOper_GetListResult;
        }
        
        public System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListResponse> SyLogOper_GetListAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogOper_GetListRequest request) {
            return base.Channel.SyLogOper_GetListAsync(request);
        }
        
        public void SyLogErrorWeb_Add(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorAdd m) {
            base.Channel.SyLogErrorWeb_Add(m);
        }
        
        public System.Threading.Tasks.Task SyLogErrorWeb_AddAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorAdd m) {
            return base.Channel.SyLogErrorWeb_AddAsync(m);
        }
        
        public void SyLogErrorApi_Add(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorAdd m) {
            base.Channel.SyLogErrorApi_Add(m);
        }
        
        public System.Threading.Tasks.Task SyLogErrorApi_AddAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorAdd m) {
            return base.Channel.SyLogErrorApi_AddAsync(m);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListResponse Kingsun.SmarterClassroom.API.BigDataService.IBigDataService.SyLogError_GetList(Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListRequest request) {
            return base.Channel.SyLogError_GetList(request);
        }
        
        public Kingsun.SmarterClassroom.API.BigDataService.SyLogErrorList[] SyLogError_GetList(int pageIndex, int pageSize, string controller, out int total) {
            Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListRequest inValue = new Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListRequest();
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.controller = controller;
            Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListResponse retVal = ((Kingsun.SmarterClassroom.API.BigDataService.IBigDataService)(this)).SyLogError_GetList(inValue);
            total = retVal.total;
            return retVal.SyLogError_GetListResult;
        }
        
        public System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListResponse> SyLogError_GetListAsync(Kingsun.SmarterClassroom.API.BigDataService.SyLogError_GetListRequest request) {
            return base.Channel.SyLogError_GetListAsync(request);
        }
        
        public void ClrLogMonitorWeb_Add(string userId, int userType, int OperId, string content) {
            base.Channel.ClrLogMonitorWeb_Add(userId, userType, OperId, content);
        }
        
        public System.Threading.Tasks.Task ClrLogMonitorWeb_AddAsync(string userId, int userType, int OperId, string content) {
            return base.Channel.ClrLogMonitorWeb_AddAsync(userId, userType, OperId, content);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListResponse Kingsun.SmarterClassroom.API.BigDataService.IBigDataService.ClrLogMonitorWeb_GetList(Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListRequest request) {
            return base.Channel.ClrLogMonitorWeb_GetList(request);
        }
        
        public Kingsun.SmarterClassroom.API.BigDataService.RoomLogList[] ClrLogMonitorWeb_GetList(int pageIndex, int pageSize, System.Nullable<System.DateTime> sdate, System.Nullable<System.DateTime> edate, out int total) {
            Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListRequest inValue = new Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListRequest();
            inValue.pageIndex = pageIndex;
            inValue.pageSize = pageSize;
            inValue.sdate = sdate;
            inValue.edate = edate;
            Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListResponse retVal = ((Kingsun.SmarterClassroom.API.BigDataService.IBigDataService)(this)).ClrLogMonitorWeb_GetList(inValue);
            total = retVal.total;
            return retVal.ClrLogMonitorWeb_GetListResult;
        }
        
        public System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListResponse> ClrLogMonitorWeb_GetListAsync(Kingsun.SmarterClassroom.API.BigDataService.ClrLogMonitorWeb_GetListRequest request) {
            return base.Channel.ClrLogMonitorWeb_GetListAsync(request);
        }
        
        public Kingsun.SmarterClassroom.API.BigDataService.RoomLogList[] ClrLogMonitorWeb_GetListAll(System.Nullable<System.DateTime> sdate, System.Nullable<System.DateTime> edate) {
            return base.Channel.ClrLogMonitorWeb_GetListAll(sdate, edate);
        }
        
        public System.Threading.Tasks.Task<Kingsun.SmarterClassroom.API.BigDataService.RoomLogList[]> ClrLogMonitorWeb_GetListAllAsync(System.Nullable<System.DateTime> sdate, System.Nullable<System.DateTime> edate) {
            return base.Channel.ClrLogMonitorWeb_GetListAllAsync(sdate, edate);
        }
    }
}
